### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by XiJingPooh** [xiofee/op8t_ops_extract#3]
>>> python3 op8t_ops_extract.py kebab_15_O.12_201015.ops kebab_15_O.12_201015
  File "<stdin>", line 1
    python3 op8t_ops_extract.py kebab_15_O.12_201015.ops kebab_15_O.12_201015
            ^
SyntaxError: invalid syntax
>>>

Am I doing something wrong?

**Comment by xiofee** [comment]
Seems you are run the python in a wrong way.
Check the python3 run first, and install all requirements.

**Comment by XiJingPooh** [comment]
I installed python3, cffi, and MinGW
